esphome:
  name: whr930

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

external_components:
  - source: esphome/components

uart:
  id: uart_bus
  tx_pin: GPIO0
  rx_pin: GPIO1
  baud_rate: 9600

fan:
- platform: whr930
  name: "Supply fan"
  type: "SUPPLY"
- platform: whr930
  name: "Exhaust fan"
  type: "EXHAUST"
- platform: whr930
  name: "fan"
  type: "BOTH"

number:
- platform: whr930
  comfort_temperature:
    name: "Comfort temperature"

sensor:
- platform: whr930
  t1_temperature:
    name: "Outside to WHR930 temperature"
  t2_temperature:
    name: "WHR930 to inside temperature"
  t3_temperature:
    name: "Inside to WHR930 temperature"
  t4_temperature:
    name: "WHR930 to outside temperature"